/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment1;
//USES AN EXAMPLE DATA SET
public class App {
  public static void main(String[] args){
    CentralControl mediator = new CentralControlimp();
    Plane plane1 = new Planeimp(mediator,"6E 2341","lat 38.8951, long -77.0364");
    Plane plane2 = new Planeimp(mediator,"8G 4367","lat 53.5432, long -82.1531");
    Plane plane3 = new Planeimp(mediator,"4E 3525","lat 37.8951, long -75.0364");
    Plane plane4 = new Planeimp(mediator,"3T 5376","lat 23.8951, long -34.0364");
    mediator.addPlane(plane1);
    mediator.addPlane(plane2);
    mediator.addPlane(plane3);
    mediator.addPlane(plane4);

    plane3.sendmsg("Currently in process of TakeOff be advised we will be entering common airspace in approxemetly 15min");
  }
}
